# load_libraries.R

# Function to load required libraries
load_required_libraries <- function() {
  library(shiny)
  library(shinydashboard)
  library(shinyWidgets)
  library(shinyFiles)
  library(fs)
  library(DT)
  library(plotly)
  library(InteractiveComplexHeatmap)
  library(ComplexHeatmap)
  library(MicrobiotaProcess)
  library(RColorBrewer)
  library(phyloseq)
  library(vegan)
  library(dplyr)
  library(tidyr)
  library(writexl)
  library(microbiome)
  library(grDevices)
  library(graphics)
  library(stats)
  library(magrittr)
  library(reshape2)
  library(utils)
  library(microViz)
  library(UpSetR)
  library(ggvenn)
  library(DirichletMultinomial)
}
